# language: python

os:
  - linux
  - osx

env:
  - VIM_VERSION=normal
  - VIM_VERSION=last
  - VIM_VERSION=neovim
  - VIM_VERSION=macvim

matrix:
  exclude:
    - os: osx
      env: VIM_VERSION=last
# neovim build fails with homebrew
# Error: undefined method `desc' for Neovim:Class
    # - os: osx
    #   env: VIM_VERSION=neovim # doesnt complete in travis
    - os: osx
      env: VIM_VERSION=macvim # doesnt complete in travis
    - os: linux
      env: VIM_VERSION=macvim # doesnt make sense for linux

install:
  - if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
      if [ "$VIM_VERSION" = 'neovim' ]; then
        HOMEBREW_NO_AUTO_UPDATE=1 brew install neovim;
      elif [ "$VIM_VERSION" = 'macvim' ]; then
        brew install macvim;
      elif [ "$VIM_VERSION" = 'normal' ]; then
        echo "use normal vim";
      else
        echo "VIM_VERSION is not set";
        exit 1;
      fi
    elif [ "$TRAVIS_OS_NAME" = 'linux' ]; then
      if [ "$VIM_VERSION" = 'last' ]; then
        sudo add-apt-repository -y ppa:fcwu-tw/ppa &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install vim;
      elif [ "$VIM_VERSION" = 'neovim' ]; then
        sudo add-apt-repository -y ppa:neovim-ppa/unstable &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install neovim;
      elif [ "$VIM_VERSION" = 'normal' ]; then
        echo "use normal vim";
      else
        echo "VIM_VERSION is not set";
        exit 1;
      fi
    fi

before_script:
  - git clone https://github.com/jreybert/vader.vim

script:
  - ./tests/run-all-ci.sh $VIM_VERSION