dist: xenial
language: minimal

matrix:
  include:
    - env: ENV=vim
      addons:
        apt:
          packages:
            - ruby
            - ruby-dev
    - env: ENV=vim-travis
      addons:
        apt:
          packages:
            - vim-nox-py2
    - env: ENV=nvim-stable
      addons:
        apt:
          sources:
            - sourceline: 'ppa:neovim-ppa/stable'
          packages:
            - neovim

install:
  - pip install --user covimerage
  - |
    set -e
    pushd /tmp
    if [ "$ENV" = vim ]; then
      rvm use system
      git clone --depth=1 https://github.com/vim/vim
      cd vim
      ./configure --with-features=huge --enable-rubyinterp --enable-pythoninterp --prefix /tmp/vim
      make
      make install
      PATH=/tmp/vim/bin:$PATH
    elif [ "$ENV" = nvim ] || [ "${ENV#nvim-}" != "$ENV" ]; then
      if [ "$ENV" = nvim ]; then
        # Install Neovim nightly (into /tmp/_neovim).
        TRAVIS_BUILD_DIR=/tmp eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"
      fi
      gem install neovim
      pip install --user pynvim
    fi
    popd

before_script: |
  git clone https://github.com/junegunn/vader.vim.git

script:
  - export TESTVIM="${ENV%%-*}"
  - $TESTVIM --version
  - VADER_TEST_VIM="$TESTVIM $TESTVIM_OPTS" ./tests/run-tests.sh